apiVersion: v1
kind: Service
metadata:
  name: confident-kalam-26b5948756-srv
  namespace: apps-release
spec:
  selector:
    app: confident-kalam-26b5948756
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: NodePort
